[package]
name = "barfly"
version = "0.1.1"
authors = ["John Quigley <jmquigs@gmail.com>"]
description = "WIP: implement osx dock/windows taskbar apps in rust"
license = "MIT"
repository = "https://github.com/jmquigs/rs-barfly"

[dependencies]
