[package]
name = "barfly"
version = "0.1.3"
authors = ["John Quigley <jmquigs@gmail.com>"]
description = "WIP. Donut use. Implement osx dock/windows taskbar apps in rust."
license = "MIT"
repository = "https://github.com/jmquigs/rs-barfly"

[dependencies]

[target.x86_64-apple-darwin.dependencies]
cocoa = "0.8"
objc = "0.2"
core-graphics = "0.8"
objc-foundation = "0.1"
objc_id = "0.1"
libc = "0.2"
