[package]
name = "barfly-simple"
version = "0.1.0"
authors = ["John Quigley <jmquigs@gmail.com>"]


[dependencies]
cocoa = "*"
objc = "*"
core-graphics = "*"
objc-foundation = "*"
objc_id = "*"
libc = "*"
barfly = "*"
